# Generated by Django 2.2 on 2019-04-25 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
