# Generated by Django 2.2 on 2019-04-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twit', '0002_auto_20190424_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
