# Generated by Django 2.2 on 2019-04-25 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twit', '0003_auto_20190424_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='userid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followings',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='like',
        ),
        migrations.AddField(
            model_name='tweet',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
