# Generated by Django 2.2 on 2019-04-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twit', '0004_auto_20190425_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
